using Org.Bukkit;
namespace TextureGenerator;

public static class MaterialExtensions
{
	public static string? DefaultParentModel(this Material material)
	{
		switch (material)
		{
			case Material.ACACIA_BOAT:
			case Material.ACACIA_DOOR:
			case Material.ACACIA_SAPLING:
			case Material.ACACIA_SIGN:
			case Material.ACTIVATOR_RAIL:
			case Material.ALLIUM:
			case Material.AMETHYST_CLUSTER:
			case Material.AMETHYST_SHARD:
			case Material.APPLE:
			case Material.ARMOR_STAND:
			case Material.AXOLOTL_BUCKET:
			case Material.AZURE_BLUET:
			case Material.BAKED_POTATO:
			case Material.BARRIER:
			case Material.BEEF:
			case Material.BEETROOT:
			case Material.BEETROOT_SEEDS:
			case Material.ARROW:
			case Material.BEETROOT_SOUP:
			case Material.BIRCH_SIGN:
			case Material.CHARCOAL:
			case Material.BELL:
			case Material.BIRCH_BOAT:
			case Material.BIRCH_DOOR:
			case Material.BIRCH_SAPLING:
			case Material.BLACK_CANDLE:
			case Material.BLACK_DYE:
			case Material.BLACK_STAINED_GLASS_PANE:
			case Material.BLAZE_POWDER:
			case Material.BLUE_CANDLE:
			case Material.BLUE_DYE:
			case Material.BLUE_ORCHID:
			case Material.BLUE_STAINED_GLASS_PANE:
			case Material.BONE_MEAL:
			case Material.BOOK:
			case Material.BOWL:
			case Material.BRAIN_CORAL:
			case Material.BRAIN_CORAL_FAN:
			case Material.BREAD:
			case Material.BREWING_STAND:
			case Material.BRICK:
			case Material.BROWN_CANDLE:
			case Material.BROWN_DYE:
			case Material.BROWN_MUSHROOM:
			case Material.BROWN_STAINED_GLASS_PANE:
			case Material.BUBBLE_CORAL:
			case Material.BUBBLE_CORAL_FAN:
			case Material.BUCKET:
			case Material.CAKE:
			case Material.CAMPFIRE:
			case Material.CANDLE:
			case Material.CARROT:
			case Material.CAULDRON:
			case Material.CHAIN:
			case Material.CHAINMAIL_BOOTS:
			case Material.CHAINMAIL_CHESTPLATE:
			case Material.CHAINMAIL_HELMET:
			case Material.CHAINMAIL_LEGGINGS:
			case Material.CHEST_MINECART:
			case Material.CHICKEN:
			case Material.CHORUS_FRUIT:
			case Material.CLAY_BALL:
			case Material.COAL:
			case Material.COBWEB:
			case Material.COCOA_BEANS:
			case Material.COD_BUCKET:
			case Material.COMMAND_BLOCK_MINECART:
			case Material.COMPARATOR:
			case Material.COOKED_BEEF:
			case Material.COOKED_CHICKEN:
			case Material.COOKED_COD:
			case Material.COOKED_MUTTON:
			case Material.COOKED_PORKCHOP:
			case Material.COOKED_SALMON:
			case Material.COOKIE:
			case Material.COPPER_INGOT:
			case Material.CORNFLOWER:
			case Material.CREEPER_BANNER_PATTERN:
			case Material.CRIMSON_DOOR:
			case Material.CRIMSON_FUNGUS:
			case Material.CRIMSON_ROOTS:
			case Material.CRIMSON_SIGN:
			case Material.CYAN_CANDLE:
			case Material.CYAN_DYE:
			case Material.CYAN_STAINED_GLASS_PANE:
			case Material.DANDELION:
			case Material.DARK_OAK_BOAT:
			case Material.DARK_OAK_DOOR:
			case Material.DARK_OAK_SAPLING:
			case Material.DARK_OAK_SIGN:
			case Material.DEAD_BRAIN_CORAL_FAN:
			case Material.DEAD_BUBBLE_CORAL:
			case Material.DEAD_BUBBLE_CORAL_FAN:
			case Material.DEAD_BUSH:
			case Material.DEAD_FIRE_CORAL:
			case Material.DEAD_FIRE_CORAL_FAN:
			case Material.DEAD_HORN_CORAL:
			case Material.DEAD_HORN_CORAL_FAN:
			case Material.DEAD_TUBE_CORAL:
			case Material.DEAD_TUBE_CORAL_FAN:
			case Material.DETECTOR_RAIL:
			case Material.DIAMOND:
			case Material.DIAMOND_BOOTS:
			case Material.DIAMOND_CHESTPLATE:
			case Material.DIAMOND_HELMET:
			case Material.DIAMOND_HORSE_ARMOR:
			case Material.DIAMOND_LEGGINGS:
			case Material.DRAGON_BREATH:
			case Material.DRIED_KELP:
			case Material.EGG:
			case Material.EMERALD:
			case Material.ENCHANTED_BOOK:
			case Material.ENCHANTED_GOLDEN_APPLE:
			case Material.ENDER_EYE:
			case Material.ENDER_PEARL:
			case Material.END_CRYSTAL:
			case Material.EXPERIENCE_BOTTLE:
			case Material.FERMENTED_SPIDER_EYE:
			case Material.FERN:
			case Material.FIREWORK_ROCKET:
			case Material.FIRE_CHARGE:
			case Material.FIRE_CORAL:
			case Material.FIRE_CORAL_FAN:
			case Material.FLINT:
			case Material.FLINT_AND_STEEL:
			case Material.FLOWER_BANNER_PATTERN:
			case Material.FLOWER_POT:
			case Material.FURNACE_MINECART:
			case Material.GHAST_TEAR:
			case Material.GLASS_BOTTLE:
			case Material.GLASS_PANE:
			case Material.GLISTERING_MELON_SLICE:
			case Material.GLOBE_BANNER_PATTERN:
			case Material.GLOWSTONE_DUST:
			case Material.GLOW_BERRIES:
			case Material.GLOW_INK_SAC:
			case Material.GLOW_LICHEN:
			case Material.GOLDEN_APPLE:
			case Material.GOLDEN_BOOTS:
			case Material.GOLDEN_CARROT:
			case Material.GOLDEN_CHESTPLATE:
			case Material.GOLDEN_HELMET:
			case Material.GOLDEN_HORSE_ARMOR:
			case Material.GOLDEN_LEGGINGS:
			case Material.COOKED_RABBIT:
			case Material.DEAD_BRAIN_CORAL:
			case Material.GOLD_INGOT:
			case Material.GOLD_NUGGET:
			case Material.GRASS:
			case Material.GRAY_CANDLE:
			case Material.GRAY_STAINED_GLASS_PANE:
			case Material.GREEN_CANDLE:
			case Material.GREEN_DYE:
			case Material.GUNPOWDER:
			case Material.HEART_OF_THE_SEA:
			case Material.HONEYCOMB:
			case Material.HONEY_BOTTLE:
			case Material.HOPPER_MINECART:
			case Material.HORN_CORAL:
			case Material.HORN_CORAL_FAN:
			case Material.INK_SAC:
			case Material.IRON_BOOTS:
			case Material.IRON_CHESTPLATE:
			case Material.IRON_DOOR:
			case Material.IRON_HELMET:
			case Material.IRON_HORSE_ARMOR:
			case Material.IRON_INGOT:
			case Material.IRON_LEGGINGS:
			case Material.IRON_NUGGET:
			case Material.JUNGLE_BOAT:
			case Material.JUNGLE_DOOR:
			case Material.JUNGLE_SAPLING:
			case Material.JUNGLE_SIGN:
			case Material.KELP:
			case Material.KNOWLEDGE_BOOK:
			case Material.LADDER:
			case Material.LANTERN:
			case Material.LAPIS_LAZULI:
			case Material.LARGE_FERN:
			case Material.LAVA_BUCKET:
			case Material.LEATHER:
			case Material.LEATHER_HORSE_ARMOR:
			case Material.LEVER:
			case Material.LIGHT:
			case Material.LIGHT_BLUE_CANDLE:
			case Material.LIGHT_BLUE_DYE:
			case Material.LIGHT_BLUE_STAINED_GLASS_PANE:
			case Material.LIGHT_GRAY_CANDLE:
			case Material.LIGHT_GRAY_DYE:
			case Material.LIGHT_GRAY_STAINED_GLASS_PANE:
			case Material.LILY_OF_THE_VALLEY:
			case Material.LILY_PAD:
			case Material.LIME_CANDLE:
			case Material.LIME_DYE:
			case Material.LIME_STAINED_GLASS_PANE:
			case Material.MAGENTA_CANDLE:
			case Material.MAGENTA_DYE:
			case Material.MAGENTA_STAINED_GLASS_PANE:
			case Material.MAGMA_CREAM:
			case Material.MAP:
			case Material.MELON_SEEDS:
			case Material.MELON_SLICE:
			case Material.MILK_BUCKET:
			case Material.MINECART:
			case Material.MOJANG_BANNER_PATTERN:
			case Material.MUSHROOM_STEW:
			case Material.MUSIC_DISC_11:
			case Material.MUSIC_DISC_13:
			case Material.MUSIC_DISC_BLOCKS:
			case Material.MUSIC_DISC_CAT:
			case Material.MUSIC_DISC_CHIRP:
			case Material.MUSIC_DISC_FAR:
			case Material.MUSIC_DISC_MALL:
			case Material.MUSIC_DISC_MELLOHI:
			case Material.MUSIC_DISC_PIGSTEP:
			case Material.MUSIC_DISC_STAL:
			case Material.MUSIC_DISC_STRAD:
			case Material.MUSIC_DISC_WAIT:
			case Material.MUSIC_DISC_WARD:
			case Material.MUTTON:
			case Material.NAME_TAG:
			case Material.NAUTILUS_SHELL:
			case Material.GRAY_DYE:
			case Material.GREEN_STAINED_GLASS_PANE:
			case Material.HOPPER:
			case Material.IRON_BARS:
			case Material.ITEM_FRAME:
			case Material.LILAC:
			case Material.NETHERITE_BOOTS:
			case Material.NETHERITE_CHESTPLATE:
			case Material.NETHERITE_HELMET:
			case Material.NETHERITE_INGOT:
			case Material.NETHERITE_LEGGINGS:
			case Material.NETHERITE_SCRAP:
			case Material.NETHER_BRICK:
			case Material.NETHER_SPROUTS:
			case Material.NETHER_STAR:
			case Material.NETHER_WART:
			case Material.OAK_BOAT:
			case Material.OAK_DOOR:
			case Material.OAK_SAPLING:
			case Material.OAK_SIGN:
			case Material.ORANGE_CANDLE:
			case Material.ORANGE_DYE:
			case Material.ORANGE_STAINED_GLASS_PANE:
			case Material.ORANGE_TULIP:
			case Material.OXEYE_DAISY:
			case Material.PAINTING:
			case Material.PAPER:
			case Material.PEONY:
			case Material.PHANTOM_MEMBRANE:
			case Material.PIGLIN_BANNER_PATTERN:
			case Material.PINK_CANDLE:
			case Material.PINK_DYE:
			case Material.PINK_STAINED_GLASS_PANE:
			case Material.PINK_TULIP:
			case Material.POISONOUS_POTATO:
			case Material.POPPED_CHORUS_FRUIT:
			case Material.POPPY:
			case Material.PORKCHOP:
			case Material.POTATO:
			case Material.POWDER_SNOW_BUCKET:
			case Material.POWERED_RAIL:
			case Material.PRISMARINE_CRYSTALS:
			case Material.PRISMARINE_SHARD:
			case Material.PUFFERFISH:
			case Material.PUFFERFISH_BUCKET:
			case Material.PUMPKIN_SEEDS:
			case Material.PURPLE_CANDLE:
			case Material.PURPLE_DYE:
			case Material.PURPLE_STAINED_GLASS_PANE:
			case Material.QUARTZ:
			case Material.RABBIT:
			case Material.RABBIT_FOOT:
			case Material.RABBIT_HIDE:
			case Material.RABBIT_STEW:
			case Material.RAIL:
			case Material.RAW_COPPER:
			case Material.RAW_IRON:
			case Material.REDSTONE:
			case Material.REDSTONE_TORCH:
			case Material.RED_CANDLE:
			case Material.RED_DYE:
			case Material.RED_MUSHROOM:
			case Material.RED_STAINED_GLASS_PANE:
			case Material.RED_TULIP:
			case Material.ROSE_BUSH:
			case Material.ROTTEN_FLESH:
			case Material.SADDLE:
			case Material.SALMON:
			case Material.SALMON_BUCKET:
			case Material.POINTED_DRIPSTONE:
			case Material.PUMPKIN_PIE:
			case Material.RAW_GOLD:
			case Material.GLOW_ITEM_FRAME:
			case Material.REPEATER:
			case Material.SCUTE:
			case Material.SEAGRASS:
			case Material.SEA_PICKLE:
			case Material.SHEARS:
			case Material.SHULKER_SHELL:
			case Material.SKULL_BANNER_PATTERN:
			case Material.SLIME_BALL:
			case Material.SNOWBALL:
			case Material.SOUL_CAMPFIRE:
			case Material.SOUL_LANTERN:
			case Material.SOUL_TORCH:
			case Material.SPECTRAL_ARROW:
			case Material.SPRUCE_BOAT:
			case Material.SPRUCE_DOOR:
			case Material.SPRUCE_SAPLING:
			case Material.SPYGLASS:
			case Material.STRING:
			case Material.STRUCTURE_VOID:
			case Material.SUGAR_CANE:
			case Material.SUNFLOWER:
			case Material.SUSPICIOUS_STEW:
			case Material.SWEET_BERRIES:
			case Material.TALL_GRASS:
			case Material.TNT_MINECART:
			case Material.TORCH:
			case Material.TOTEM_OF_UNDYING:
			case Material.TRIDENT:
			case Material.TRIPWIRE_HOOK:
			case Material.TROPICAL_FISH:
			case Material.TROPICAL_FISH_BUCKET:
			case Material.TUBE_CORAL:
			case Material.TUBE_CORAL_FAN:
			case Material.TURTLE_EGG:
			case Material.TURTLE_HELMET:
			case Material.TWISTING_VINES:
			case Material.VINE:
			case Material.WARPED_DOOR:
			case Material.WARPED_FUNGUS:
			case Material.WARPED_ROOTS:
			case Material.WARPED_SIGN:
			case Material.WATER_BUCKET:
			case Material.WEEPING_VINES:
			case Material.WHEAT:
			case Material.WHEAT_SEEDS:
			case Material.WHITE_CANDLE:
			case Material.WHITE_DYE:
			case Material.WHITE_STAINED_GLASS_PANE:
			case Material.WHITE_TULIP:
			case Material.WITHER_ROSE:
			case Material.WRITABLE_BOOK:
			case Material.YELLOW_CANDLE:
			case Material.YELLOW_DYE:
			case Material.YELLOW_STAINED_GLASS_PANE:
			case Material.SPIDER_EYE:
			case Material.SPRUCE_SIGN:
			case Material.SUGAR:
			case Material.WRITTEN_BOOK:
				return "minecraft:item/generated";
			case Material.ACACIA_BUTTON:
				return "minecraft:block/acacia_button_inventory";
			case Material.ACACIA_FENCE:
				return "minecraft:block/acacia_fence_inventory";
			case Material.ACACIA_FENCE_GATE:
				return "minecraft:block/acacia_fence_gate";
			case Material.ACACIA_LEAVES:
				return "minecraft:block/acacia_leaves";
			case Material.ACACIA_LOG:
				return "minecraft:block/acacia_log";
			case Material.ACACIA_PLANKS:
				return "minecraft:block/acacia_planks";
			case Material.ACACIA_PRESSURE_PLATE:
				return "minecraft:block/acacia_pressure_plate";
			case Material.ACACIA_SLAB:
				return "minecraft:block/acacia_slab";
			case Material.ACACIA_STAIRS:
				return "minecraft:block/acacia_stairs";
			case Material.ACACIA_TRAPDOOR:
				return "minecraft:block/acacia_trapdoor_bottom";
			case Material.AIR:
				return null;
			case Material.AXOLOTL_SPAWN_EGG:
			case Material.BAT_SPAWN_EGG:
			case Material.BEE_SPAWN_EGG:
			case Material.BLAZE_SPAWN_EGG:
			case Material.CAT_SPAWN_EGG:
			case Material.CAVE_SPIDER_SPAWN_EGG:
			case Material.CHICKEN_SPAWN_EGG:
			case Material.COD_SPAWN_EGG:
			case Material.COW_SPAWN_EGG:
			case Material.CREEPER_SPAWN_EGG:
			case Material.DOLPHIN_SPAWN_EGG:
			case Material.DONKEY_SPAWN_EGG:
			case Material.DROWNED_SPAWN_EGG:
			case Material.ELDER_GUARDIAN_SPAWN_EGG:
			case Material.ENDERMAN_SPAWN_EGG:
			case Material.ENDERMITE_SPAWN_EGG:
			case Material.EVOKER_SPAWN_EGG:
			case Material.FOX_SPAWN_EGG:
			case Material.GHAST_SPAWN_EGG:
			case Material.GLOW_SQUID_SPAWN_EGG:
			case Material.GOAT_SPAWN_EGG:
			case Material.GUARDIAN_SPAWN_EGG:
			case Material.HOGLIN_SPAWN_EGG:
			case Material.HORSE_SPAWN_EGG:
			case Material.HUSK_SPAWN_EGG:
			case Material.MAGMA_CUBE_SPAWN_EGG:
			case Material.MOOSHROOM_SPAWN_EGG:
			case Material.MULE_SPAWN_EGG:
			case Material.LLAMA_SPAWN_EGG:
			case Material.OCELOT_SPAWN_EGG:
			case Material.PANDA_SPAWN_EGG:
			case Material.PARROT_SPAWN_EGG:
			case Material.PHANTOM_SPAWN_EGG:
			case Material.PIGLIN_BRUTE_SPAWN_EGG:
			case Material.PIGLIN_SPAWN_EGG:
			case Material.PIG_SPAWN_EGG:
			case Material.PILLAGER_SPAWN_EGG:
			case Material.POLAR_BEAR_SPAWN_EGG:
			case Material.PUFFERFISH_SPAWN_EGG:
			case Material.RABBIT_SPAWN_EGG:
			case Material.RAVAGER_SPAWN_EGG:
			case Material.SALMON_SPAWN_EGG:
			case Material.SHEEP_SPAWN_EGG:
			case Material.SHULKER_SPAWN_EGG:
			case Material.SILVERFISH_SPAWN_EGG:
			case Material.SKELETON_SPAWN_EGG:
			case Material.SLIME_SPAWN_EGG:
			case Material.SPIDER_SPAWN_EGG:
			case Material.SQUID_SPAWN_EGG:
			case Material.STRAY_SPAWN_EGG:
			case Material.STRIDER_SPAWN_EGG:
			case Material.TRADER_LLAMA_SPAWN_EGG:
			case Material.TROPICAL_FISH_SPAWN_EGG:
			case Material.TURTLE_SPAWN_EGG:
			case Material.VEX_SPAWN_EGG:
			case Material.VILLAGER_SPAWN_EGG:
			case Material.VINDICATOR_SPAWN_EGG:
			case Material.WANDERING_TRADER_SPAWN_EGG:
			case Material.WITCH_SPAWN_EGG:
			case Material.WITHER_SKELETON_SPAWN_EGG:
			case Material.WOLF_SPAWN_EGG:
			case Material.ZOGLIN_SPAWN_EGG:
			case Material.ZOMBIE_HORSE_SPAWN_EGG:
			case Material.ZOMBIE_SPAWN_EGG:
			case Material.ZOMBIE_VILLAGER_SPAWN_EGG:
			case Material.ZOMBIFIED_PIGLIN_SPAWN_EGG:
			case Material.SKELETON_HORSE_SPAWN_EGG:
				return "minecraft:item/template_spawn_egg";
			case Material.AMETHYST_BLOCK:
				return "minecraft:block/amethyst_block";
			case Material.ANCIENT_DEBRIS:
				return "minecraft:block/ancient_debris";
			case Material.ANDESITE:
				return "minecraft:block/andesite";
			case Material.ANDESITE_SLAB:
				return "minecraft:block/andesite_slab";
			case Material.ANDESITE_STAIRS:
				return "minecraft:block/andesite_stairs";
			case Material.ANDESITE_WALL:
				return "minecraft:block/andesite_wall_inventory";
			case Material.ANVIL:
				return "minecraft:block/anvil";
			case Material.AZALEA:
				return "minecraft:block/azalea";
			case Material.AZALEA_LEAVES:
				return "minecraft:block/azalea_leaves";
			case Material.BAMBOO:
			case Material.BLAZE_ROD:
			case Material.DIAMOND_AXE:
			case Material.DIAMOND_HOE:
			case Material.DIAMOND_PICKAXE:
			case Material.DIAMOND_SHOVEL:
			case Material.DIAMOND_SWORD:
			case Material.GOLDEN_AXE:
			case Material.GOLDEN_HOE:
			case Material.GOLDEN_PICKAXE:
			case Material.GOLDEN_SHOVEL:
			case Material.GOLDEN_SWORD:
			case Material.DEBUG_STICK:
			case Material.IRON_AXE:
			case Material.IRON_HOE:
			case Material.IRON_PICKAXE:
			case Material.IRON_SHOVEL:
			case Material.IRON_SWORD:
			case Material.NETHERITE_HOE:
			case Material.NETHERITE_PICKAXE:
			case Material.NETHERITE_SHOVEL:
			case Material.NETHERITE_SWORD:
			case Material.NETHERITE_AXE:
			case Material.STICK:
			case Material.STONE_AXE:
			case Material.STONE_HOE:
			case Material.STONE_PICKAXE:
			case Material.STONE_SHOVEL:
			case Material.STONE_SWORD:
			case Material.WOODEN_AXE:
			case Material.WOODEN_HOE:
			case Material.WOODEN_PICKAXE:
			case Material.WOODEN_SHOVEL:
			case Material.WOODEN_SWORD:
				return "minecraft:item/handheld";
			case Material.BARREL:
				return "minecraft:block/barrel";
			case Material.BASALT:
				return "minecraft:block/basalt";
			case Material.BEACON:
				return "minecraft:block/beacon";
			case Material.BEDROCK:
				return "minecraft:block/bedrock";
			case Material.BEEHIVE:
				return "minecraft:block/beehive";
			case Material.ACACIA_WOOD:
				return "minecraft:block/acacia_wood";
			case Material.BLACK_SHULKER_BOX:
			case Material.BLUE_SHULKER_BOX:
			case Material.BROWN_SHULKER_BOX:
			case Material.CYAN_SHULKER_BOX:
			case Material.GRAY_SHULKER_BOX:
			case Material.GREEN_SHULKER_BOX:
			case Material.LIGHT_BLUE_SHULKER_BOX:
			case Material.LIGHT_GRAY_SHULKER_BOX:
			case Material.LIME_SHULKER_BOX:
			case Material.MAGENTA_SHULKER_BOX:
			case Material.ORANGE_SHULKER_BOX:
			case Material.PINK_SHULKER_BOX:
			case Material.PURPLE_SHULKER_BOX:
			case Material.RED_SHULKER_BOX:
			case Material.SHULKER_BOX:
			case Material.WHITE_SHULKER_BOX:
			case Material.YELLOW_SHULKER_BOX:
				return "minecraft:item/template_shulker_box";
			case Material.BLUE_ICE:
				return "minecraft:block/blue_ice";
			case Material.BRAIN_CORAL_BLOCK:
				return "minecraft:block/brain_coral_block";
			case Material.BROWN_GLAZED_TERRACOTTA:
				return "minecraft:block/brown_glazed_terracotta";
			case Material.CALCITE:
				return "minecraft:block/calcite";
			case Material.CLAY:
				return "minecraft:block/clay";
			case Material.BEE_NEST:
				return "minecraft:block/bee_nest";
			case Material.BIG_DRIPLEAF:
				return "minecraft:block/big_dripleaf";
			case Material.BIRCH_BUTTON:
				return "minecraft:block/birch_button_inventory";
			case Material.BIRCH_FENCE:
				return "minecraft:block/birch_fence_inventory";
			case Material.BIRCH_FENCE_GATE:
				return "minecraft:block/birch_fence_gate";
			case Material.BIRCH_LEAVES:
				return "minecraft:block/birch_leaves";
			case Material.BIRCH_LOG:
				return "minecraft:block/birch_log";
			case Material.BIRCH_PLANKS:
				return "minecraft:block/birch_planks";
			case Material.BIRCH_PRESSURE_PLATE:
				return "minecraft:block/birch_pressure_plate";
			case Material.BIRCH_SLAB:
				return "minecraft:block/birch_slab";
			case Material.BIRCH_STAIRS:
				return "minecraft:block/birch_stairs";
			case Material.BIRCH_TRAPDOOR:
				return "minecraft:block/birch_trapdoor_bottom";
			case Material.BIRCH_WOOD:
				return "minecraft:block/birch_wood";
			case Material.BLACKSTONE:
				return "minecraft:block/blackstone";
			case Material.BLACKSTONE_SLAB:
				return "minecraft:block/blackstone_slab";
			case Material.BLACKSTONE_STAIRS:
				return "minecraft:block/blackstone_stairs";
			case Material.BLACKSTONE_WALL:
				return "minecraft:block/blackstone_wall_inventory";
			case Material.BLACK_BANNER:
			case Material.BLUE_BANNER:
			case Material.BROWN_BANNER:
			case Material.CYAN_BANNER:
			case Material.GRAY_BANNER:
			case Material.GREEN_BANNER:
			case Material.LIGHT_BLUE_BANNER:
			case Material.LIGHT_GRAY_BANNER:
			case Material.LIME_BANNER:
			case Material.MAGENTA_BANNER:
			case Material.ORANGE_BANNER:
			case Material.PINK_BANNER:
			case Material.PURPLE_BANNER:
			case Material.RED_BANNER:
			case Material.WHITE_BANNER:
			case Material.YELLOW_BANNER:
				return "minecraft:item/template_banner";
			case Material.BLACK_BED:
			case Material.BLUE_BED:
			case Material.BROWN_BED:
			case Material.CYAN_BED:
			case Material.GRAY_BED:
			case Material.GREEN_BED:
			case Material.LIGHT_BLUE_BED:
			case Material.LIGHT_GRAY_BED:
			case Material.LIME_BED:
			case Material.MAGENTA_BED:
			case Material.ORANGE_BED:
			case Material.PURPLE_BED:
			case Material.RED_BED:
			case Material.PINK_BED:
			case Material.WHITE_BED:
			case Material.YELLOW_BED:
				return "minecraft:item/template_bed";
			case Material.BLACK_CARPET:
				return "minecraft:block/black_carpet";
			case Material.BLACK_CONCRETE:
				return "minecraft:block/black_concrete";
			case Material.BLACK_CONCRETE_POWDER:
				return "minecraft:block/black_concrete_powder";
			case Material.BLACK_GLAZED_TERRACOTTA:
				return "minecraft:block/black_glazed_terracotta";
			case Material.BLACK_STAINED_GLASS:
				return "minecraft:block/black_stained_glass";
			case Material.BLACK_TERRACOTTA:
				return "minecraft:block/black_terracotta";
			case Material.BLACK_WOOL:
				return "minecraft:block/black_wool";
			case Material.BLAST_FURNACE:
				return "minecraft:block/blast_furnace";
			case Material.BLUE_CARPET:
				return "minecraft:block/blue_carpet";
			case Material.BLUE_CONCRETE:
				return "minecraft:block/blue_concrete";
			case Material.BLUE_CONCRETE_POWDER:
				return "minecraft:block/blue_concrete_powder";
			case Material.BLUE_GLAZED_TERRACOTTA:
				return "minecraft:block/blue_glazed_terracotta";
			case Material.BLUE_STAINED_GLASS:
				return "minecraft:block/blue_stained_glass";
			case Material.BLUE_TERRACOTTA:
				return "minecraft:block/blue_terracotta";
			case Material.BLUE_WOOL:
				return "minecraft:block/blue_wool";
			case Material.BONE:
				return "item/handheld";
			case Material.BONE_BLOCK:
				return "minecraft:block/bone_block";
			case Material.BOOKSHELF:
				return "minecraft:block/bookshelf";
			case Material.BOW:
			case Material.BUNDLE:
			case Material.CLOCK:
			case Material.COD:
			case Material.COMPASS:
			case Material.CROSSBOW:
			case Material.ELYTRA:
			case Material.FEATHER:
			case Material.FIREWORK_STAR:
			case Material.FILLED_MAP:
			case Material.HANGING_ROOTS:
			case Material.LEAD:
			case Material.LEATHER_BOOTS:
			case Material.LEATHER_CHESTPLATE:
			case Material.LEATHER_LEGGINGS:
			case Material.LINGERING_POTION:
			case Material.LEATHER_HELMET:
			case Material.POTION:
			case Material.SPLASH_POTION:
			case Material.TIPPED_ARROW:
				return "item/generated";
			case Material.BRICKS:
				return "minecraft:block/bricks";
			case Material.BRICK_SLAB:
				return "minecraft:block/brick_slab";
			case Material.BRICK_STAIRS:
				return "minecraft:block/brick_stairs";
			case Material.BRICK_WALL:
				return "minecraft:block/brick_wall_inventory";
			case Material.BROWN_CARPET:
				return "minecraft:block/brown_carpet";
			case Material.BROWN_CONCRETE:
				return "minecraft:block/brown_concrete";
			case Material.BROWN_CONCRETE_POWDER:
				return "minecraft:block/brown_concrete_powder";
			case Material.BROWN_MUSHROOM_BLOCK:
				return "minecraft:block/brown_mushroom_block_inventory";
			case Material.BROWN_STAINED_GLASS:
				return "minecraft:block/brown_stained_glass";
			case Material.BROWN_TERRACOTTA:
				return "minecraft:block/brown_terracotta";
			case Material.BROWN_WOOL:
				return "minecraft:block/brown_wool";
			case Material.BUBBLE_CORAL_BLOCK:
				return "minecraft:block/bubble_coral_block";
			case Material.BUDDING_AMETHYST:
				return "minecraft:block/budding_amethyst";
			case Material.CACTUS:
				return "minecraft:block/cactus";
			case Material.CARROT_ON_A_STICK:
			case Material.WARPED_FUNGUS_ON_A_STICK:
				return "minecraft:item/handheld_rod";
			case Material.CARTOGRAPHY_TABLE:
				return "minecraft:block/cartography_table";
			case Material.CARVED_PUMPKIN:
				return "minecraft:block/carved_pumpkin";
			case Material.CHAIN_COMMAND_BLOCK:
				return "minecraft:block/chain_command_block";
			case Material.CHEST:
			case Material.CONDUIT:
			case Material.SHIELD:
				return "builtin/entity";
			case Material.CHIPPED_ANVIL:
				return "minecraft:block/chipped_anvil";
			case Material.CHISELED_DEEPSLATE:
				return "minecraft:block/chiseled_deepslate";
			case Material.CHISELED_NETHER_BRICKS:
				return "minecraft:block/chiseled_nether_bricks";
			case Material.CHISELED_POLISHED_BLACKSTONE:
				return "minecraft:block/chiseled_polished_blackstone";
			case Material.CHISELED_QUARTZ_BLOCK:
				return "minecraft:block/chiseled_quartz_block";
			case Material.CHISELED_RED_SANDSTONE:
				return "minecraft:block/chiseled_red_sandstone";
			case Material.CHISELED_SANDSTONE:
				return "minecraft:block/chiseled_sandstone";
			case Material.CHISELED_STONE_BRICKS:
			case Material.INFESTED_CHISELED_STONE_BRICKS:
				return "minecraft:block/chiseled_stone_bricks";
			case Material.CHORUS_FLOWER:
				return "minecraft:block/chorus_flower";
			case Material.CHORUS_PLANT:
				return "minecraft:block/chorus_plant";
			case Material.COAL_BLOCK:
				return "minecraft:block/coal_block";
			case Material.COAL_ORE:
				return "minecraft:block/coal_ore";
			case Material.COARSE_DIRT:
				return "minecraft:block/coarse_dirt";
			case Material.COBBLED_DEEPSLATE:
				return "minecraft:block/cobbled_deepslate";
			case Material.COBBLED_DEEPSLATE_SLAB:
				return "minecraft:block/cobbled_deepslate_slab";
			case Material.COBBLED_DEEPSLATE_WALL:
				return "minecraft:block/cobbled_deepslate_wall_inventory";
			case Material.COBBLESTONE:
			case Material.INFESTED_COBBLESTONE:
				return "minecraft:block/cobblestone";
			case Material.COBBLESTONE_SLAB:
				return "minecraft:block/cobblestone_slab";
			case Material.COBBLESTONE_STAIRS:
				return "minecraft:block/cobblestone_stairs";
			case Material.COBBLESTONE_WALL:
				return "minecraft:block/cobblestone_wall_inventory";
			case Material.COMMAND_BLOCK:
				return "minecraft:block/command_block";
			case Material.COMPOSTER:
				return "minecraft:block/composter";
			case Material.COPPER_BLOCK:
			case Material.WAXED_COPPER_BLOCK:
				return "minecraft:block/copper_block";
			case Material.COPPER_ORE:
				return "minecraft:block/copper_ore";
			case Material.CRACKED_DEEPSLATE_BRICKS:
				return "minecraft:block/cracked_deepslate_bricks";
			case Material.CRACKED_DEEPSLATE_TILES:
				return "minecraft:block/cracked_deepslate_tiles";
			case Material.CRACKED_NETHER_BRICKS:
				return "minecraft:block/cracked_nether_bricks";
			case Material.CRACKED_POLISHED_BLACKSTONE_BRICKS:
				return "minecraft:block/cracked_polished_blackstone_bricks";
			case Material.CRACKED_STONE_BRICKS:
			case Material.INFESTED_CRACKED_STONE_BRICKS:
				return "minecraft:block/cracked_stone_bricks";
			case Material.CRAFTING_TABLE:
				return "minecraft:block/crafting_table";
			case Material.CREEPER_HEAD:
			case Material.PLAYER_HEAD:
			case Material.SKELETON_SKULL:
			case Material.WITHER_SKELETON_SKULL:
			case Material.ZOMBIE_HEAD:
				return "minecraft:item/template_skull";
			case Material.CRIMSON_FENCE:
				return "minecraft:block/crimson_fence_inventory";
			case Material.CRIMSON_FENCE_GATE:
				return "minecraft:block/crimson_fence_gate";
			case Material.CRIMSON_HYPHAE:
				return "minecraft:block/crimson_hyphae";
			case Material.CRIMSON_NYLIUM:
				return "minecraft:block/crimson_nylium";
			case Material.CRIMSON_PLANKS:
				return "minecraft:block/crimson_planks";
			case Material.CRIMSON_PRESSURE_PLATE:
				return "minecraft:block/crimson_pressure_plate";
			case Material.CRIMSON_SLAB:
				return "minecraft:block/crimson_slab";
			case Material.CRIMSON_STAIRS:
				return "minecraft:block/crimson_stairs";
			case Material.CRIMSON_STEM:
				return "minecraft:block/crimson_stem";
			case Material.CRIMSON_TRAPDOOR:
				return "minecraft:block/crimson_trapdoor_bottom";
			case Material.CRYING_OBSIDIAN:
				return "minecraft:block/crying_obsidian";
			case Material.CUT_COPPER:
			case Material.WAXED_CUT_COPPER:
				return "minecraft:block/cut_copper";
			case Material.CUT_COPPER_SLAB:
			case Material.WAXED_CUT_COPPER_SLAB:
				return "minecraft:block/cut_copper_slab";
			case Material.CUT_COPPER_STAIRS:
			case Material.WAXED_CUT_COPPER_STAIRS:
				return "minecraft:block/cut_copper_stairs";
			case Material.CUT_RED_SANDSTONE:
				return "minecraft:block/cut_red_sandstone";
			case Material.CUT_RED_SANDSTONE_SLAB:
				return "minecraft:block/cut_red_sandstone_slab";
			case Material.CUT_SANDSTONE:
				return "minecraft:block/cut_sandstone";
			case Material.CUT_SANDSTONE_SLAB:
				return "minecraft:block/cut_sandstone_slab";
			case Material.CYAN_CARPET:
				return "minecraft:block/cyan_carpet";
			case Material.CYAN_CONCRETE_POWDER:
				return "minecraft:block/cyan_concrete_powder";
			case Material.CYAN_GLAZED_TERRACOTTA:
				return "minecraft:block/cyan_glazed_terracotta";
			case Material.CYAN_STAINED_GLASS:
				return "minecraft:block/cyan_stained_glass";
			case Material.CYAN_TERRACOTTA:
				return "minecraft:block/cyan_terracotta";
			case Material.CYAN_WOOL:
				return "minecraft:block/cyan_wool";
			case Material.DAMAGED_ANVIL:
				return "minecraft:block/damaged_anvil";
			case Material.DARK_OAK_BUTTON:
				return "minecraft:block/dark_oak_button_inventory";
			case Material.DARK_OAK_FENCE:
				return "minecraft:block/dark_oak_fence_inventory";
			case Material.DARK_OAK_LEAVES:
				return "minecraft:block/dark_oak_leaves";
			case Material.DARK_OAK_LOG:
				return "minecraft:block/dark_oak_log";
			case Material.DARK_OAK_PLANKS:
				return "minecraft:block/dark_oak_planks";
			case Material.DARK_OAK_PRESSURE_PLATE:
				return "minecraft:block/dark_oak_pressure_plate";
			case Material.DARK_OAK_SLAB:
				return "minecraft:block/dark_oak_slab";
			case Material.DARK_OAK_STAIRS:
				return "minecraft:block/dark_oak_stairs";
			case Material.DARK_OAK_TRAPDOOR:
				return "minecraft:block/dark_oak_trapdoor_bottom";
			case Material.DARK_OAK_WOOD:
				return "minecraft:block/dark_oak_wood";
			case Material.DARK_PRISMARINE:
				return "minecraft:block/dark_prismarine";
			case Material.DARK_PRISMARINE_SLAB:
				return "minecraft:block/dark_prismarine_slab";
			case Material.DARK_PRISMARINE_STAIRS:
				return "minecraft:block/dark_prismarine_stairs";
			case Material.DAYLIGHT_DETECTOR:
				return "minecraft:block/daylight_detector";
			case Material.DEAD_BRAIN_CORAL_BLOCK:
				return "minecraft:block/dead_brain_coral_block";
			case Material.DEAD_BUBBLE_CORAL_BLOCK:
				return "minecraft:block/dead_bubble_coral_block";
			case Material.DEAD_FIRE_CORAL_BLOCK:
				return "minecraft:block/dead_fire_coral_block";
			case Material.DEAD_HORN_CORAL_BLOCK:
				return "minecraft:block/dead_horn_coral_block";
			case Material.DEAD_TUBE_CORAL_BLOCK:
				return "minecraft:block/dead_tube_coral_block";
			case Material.DEEPSLATE:
			case Material.INFESTED_DEEPSLATE:
				return "minecraft:block/deepslate";
			case Material.DEEPSLATE_BRICKS:
				return "minecraft:block/deepslate_bricks";
			case Material.DEEPSLATE_BRICK_SLAB:
				return "minecraft:block/deepslate_brick_slab";
			case Material.DEEPSLATE_BRICK_STAIRS:
				return "minecraft:block/deepslate_brick_stairs";
			case Material.DEEPSLATE_BRICK_WALL:
				return "minecraft:block/deepslate_brick_wall_inventory";
			case Material.DEEPSLATE_COAL_ORE:
				return "minecraft:block/deepslate_coal_ore";
			case Material.DEEPSLATE_COPPER_ORE:
				return "minecraft:block/deepslate_copper_ore";
			case Material.DEEPSLATE_DIAMOND_ORE:
				return "minecraft:block/deepslate_diamond_ore";
			case Material.DEEPSLATE_EMERALD_ORE:
				return "minecraft:block/deepslate_emerald_ore";
			case Material.DEEPSLATE_GOLD_ORE:
				return "minecraft:block/deepslate_gold_ore";
			case Material.DEEPSLATE_IRON_ORE:
				return "minecraft:block/deepslate_iron_ore";
			case Material.DEEPSLATE_LAPIS_ORE:
				return "minecraft:block/deepslate_lapis_ore";
			case Material.DEEPSLATE_REDSTONE_ORE:
				return "minecraft:block/deepslate_redstone_ore";
			case Material.DEEPSLATE_TILES:
				return "minecraft:block/deepslate_tiles";
			case Material.DEEPSLATE_TILE_SLAB:
				return "minecraft:block/deepslate_tile_slab";
			case Material.DEEPSLATE_TILE_WALL:
				return "minecraft:block/deepslate_tile_wall_inventory";
			case Material.DIAMOND_BLOCK:
				return "minecraft:block/diamond_block";
			case Material.DIAMOND_ORE:
				return "minecraft:block/diamond_ore";
			case Material.DIORITE:
				return "minecraft:block/diorite";
			case Material.DIORITE_STAIRS:
				return "minecraft:block/diorite_stairs";
			case Material.DIORITE_WALL:
				return "minecraft:block/diorite_wall_inventory";
			case Material.DIRT:
				return "minecraft:block/dirt";
			case Material.DIRT_PATH:
				return "minecraft:block/dirt_path";
			case Material.DISPENSER:
				return "minecraft:block/dispenser";
			case Material.DRAGON_EGG:
				return "minecraft:block/dragon_egg";
			case Material.DRAGON_HEAD:
				return "item/template_skull";
			case Material.DRIED_KELP_BLOCK:
				return "minecraft:block/dried_kelp_block";
			case Material.DRIPSTONE_BLOCK:
				return "minecraft:block/dripstone_block";
			case Material.DROPPER:
				return "minecraft:block/dropper";
			case Material.EMERALD_BLOCK:
				return "minecraft:block/emerald_block";
			case Material.EMERALD_ORE:
				return "minecraft:block/emerald_ore";
			case Material.ENCHANTING_TABLE:
				return "minecraft:block/enchanting_table";
			case Material.ENDER_CHEST:
			case Material.TRAPPED_CHEST:
				return "item/chest";
			case Material.END_ROD:
				return "minecraft:block/end_rod";
			case Material.END_STONE:
				return "minecraft:block/end_stone";
			case Material.END_STONE_BRICKS:
				return "minecraft:block/end_stone_bricks";
			case Material.END_STONE_BRICK_SLAB:
				return "minecraft:block/end_stone_brick_slab";
			case Material.END_STONE_BRICK_STAIRS:
				return "minecraft:block/end_stone_brick_stairs";
			case Material.END_STONE_BRICK_WALL:
				return "minecraft:block/end_stone_brick_wall_inventory";
			case Material.EXPOSED_COPPER:
			case Material.WAXED_EXPOSED_COPPER:
				return "minecraft:block/exposed_copper";
			case Material.EXPOSED_CUT_COPPER:
			case Material.WAXED_EXPOSED_CUT_COPPER:
				return "minecraft:block/exposed_cut_copper";
			case Material.EXPOSED_CUT_COPPER_SLAB:
			case Material.WAXED_EXPOSED_CUT_COPPER_SLAB:
				return "minecraft:block/exposed_cut_copper_slab";
			case Material.EXPOSED_CUT_COPPER_STAIRS:
			case Material.WAXED_EXPOSED_CUT_COPPER_STAIRS:
				return "minecraft:block/exposed_cut_copper_stairs";
			case Material.FARMLAND:
				return "minecraft:block/farmland";
			case Material.FIRE_CORAL_BLOCK:
				return "minecraft:block/fire_coral_block";
			case Material.FISHING_ROD:
				return "item/handheld_rod";
			case Material.FLETCHING_TABLE:
				return "minecraft:block/fletching_table";
			case Material.FLOWERING_AZALEA:
				return "minecraft:block/flowering_azalea";
			case Material.FLOWERING_AZALEA_LEAVES:
				return "minecraft:block/flowering_azalea_leaves";
			case Material.FURNACE:
				return "minecraft:block/furnace";
			case Material.GILDED_BLACKSTONE:
				return "minecraft:block/gilded_blackstone";
			case Material.GLASS:
				return "minecraft:block/glass";
			case Material.GLOWSTONE:
				return "minecraft:block/glowstone";
			case Material.CRIMSON_BUTTON:
				return "minecraft:block/crimson_button_inventory";
			case Material.CYAN_CONCRETE:
				return "minecraft:block/cyan_concrete";
			case Material.DARK_OAK_FENCE_GATE:
				return "minecraft:block/dark_oak_fence_gate";
			case Material.DEEPSLATE_TILE_STAIRS:
				return "minecraft:block/deepslate_tile_stairs";
			case Material.DIORITE_SLAB:
				return "minecraft:block/diorite_slab";
			case Material.END_PORTAL_FRAME:
				return "minecraft:block/end_portal_frame";
			case Material.GOLD_ORE:
				return "minecraft:block/gold_ore";
			case Material.GRANITE:
				return "minecraft:block/granite";
			case Material.GRANITE_SLAB:
				return "minecraft:block/granite_slab";
			case Material.GRANITE_STAIRS:
				return "minecraft:block/granite_stairs";
			case Material.GRANITE_WALL:
				return "minecraft:block/granite_wall_inventory";
			case Material.GRASS_BLOCK:
				return "minecraft:block/grass_block";
			case Material.GRAVEL:
				return "minecraft:block/gravel";
			case Material.GRAY_CARPET:
				return "minecraft:block/gray_carpet";
			case Material.GRAY_CONCRETE:
				return "minecraft:block/gray_concrete";
			case Material.GRAY_CONCRETE_POWDER:
				return "minecraft:block/gray_concrete_powder";
			case Material.GRAY_GLAZED_TERRACOTTA:
				return "minecraft:block/gray_glazed_terracotta";
			case Material.GRAY_STAINED_GLASS:
				return "minecraft:block/gray_stained_glass";
			case Material.GRAY_TERRACOTTA:
				return "minecraft:block/gray_terracotta";
			case Material.GRAY_WOOL:
				return "minecraft:block/gray_wool";
			case Material.GREEN_CARPET:
				return "minecraft:block/green_carpet";
			case Material.GREEN_CONCRETE:
				return "minecraft:block/green_concrete";
			case Material.GREEN_CONCRETE_POWDER:
				return "minecraft:block/green_concrete_powder";
			case Material.GREEN_GLAZED_TERRACOTTA:
				return "minecraft:block/green_glazed_terracotta";
			case Material.GREEN_STAINED_GLASS:
				return "minecraft:block/green_stained_glass";
			case Material.GREEN_TERRACOTTA:
				return "minecraft:block/green_terracotta";
			case Material.GREEN_WOOL:
				return "minecraft:block/green_wool";
			case Material.GRINDSTONE:
				return "minecraft:block/grindstone";
			case Material.HAY_BLOCK:
				return "minecraft:block/hay_block";
			case Material.HEAVY_WEIGHTED_PRESSURE_PLATE:
				return "minecraft:block/heavy_weighted_pressure_plate";
			case Material.HONEYCOMB_BLOCK:
				return "minecraft:block/honeycomb_block";
			case Material.HONEY_BLOCK:
				return "minecraft:block/honey_block";
			case Material.HORN_CORAL_BLOCK:
				return "minecraft:block/horn_coral_block";
			case Material.ICE:
				return "minecraft:block/ice";
			case Material.INFESTED_MOSSY_STONE_BRICKS:
			case Material.MOSSY_STONE_BRICKS:
				return "minecraft:block/mossy_stone_bricks";
			case Material.INFESTED_STONE:
			case Material.STONE:
				return "minecraft:block/stone";
			case Material.INFESTED_STONE_BRICKS:
			case Material.STONE_BRICKS:
				return "minecraft:block/stone_bricks";
			case Material.IRON_BLOCK:
				return "minecraft:block/iron_block";
			case Material.IRON_ORE:
				return "minecraft:block/iron_ore";
			case Material.IRON_TRAPDOOR:
				return "minecraft:block/iron_trapdoor_bottom";
			case Material.JACK_O_LANTERN:
				return "minecraft:block/jack_o_lantern";
			case Material.JIGSAW:
				return "minecraft:block/jigsaw";
			case Material.JUKEBOX:
				return "minecraft:block/jukebox";
			case Material.JUNGLE_BUTTON:
				return "minecraft:block/jungle_button_inventory";
			case Material.JUNGLE_FENCE:
				return "minecraft:block/jungle_fence_inventory";
			case Material.JUNGLE_FENCE_GATE:
				return "minecraft:block/jungle_fence_gate";
			case Material.JUNGLE_LEAVES:
				return "minecraft:block/jungle_leaves";
			case Material.JUNGLE_LOG:
				return "minecraft:block/jungle_log";
			case Material.JUNGLE_PLANKS:
				return "minecraft:block/jungle_planks";
			case Material.JUNGLE_PRESSURE_PLATE:
				return "minecraft:block/jungle_pressure_plate";
			case Material.JUNGLE_STAIRS:
				return "minecraft:block/jungle_stairs";
			case Material.JUNGLE_TRAPDOOR:
				return "minecraft:block/jungle_trapdoor_bottom";
			case Material.JUNGLE_WOOD:
				return "minecraft:block/jungle_wood";
			case Material.LAPIS_BLOCK:
				return "minecraft:block/lapis_block";
			case Material.LAPIS_ORE:
				return "minecraft:block/lapis_ore";
			case Material.LARGE_AMETHYST_BUD:
			case Material.MEDIUM_AMETHYST_BUD:
			case Material.SMALL_AMETHYST_BUD:
				return "item/amethyst_bud";
			case Material.LECTERN:
				return "minecraft:block/lectern";
			case Material.LIGHTNING_ROD:
				return "minecraft:block/lightning_rod";
			case Material.LIGHT_BLUE_CARPET:
				return "minecraft:block/light_blue_carpet";
			case Material.LIGHT_BLUE_CONCRETE:
				return "minecraft:block/light_blue_concrete";
			case Material.LIGHT_BLUE_CONCRETE_POWDER:
				return "minecraft:block/light_blue_concrete_powder";
			case Material.LIGHT_BLUE_GLAZED_TERRACOTTA:
				return "minecraft:block/light_blue_glazed_terracotta";
			case Material.LIGHT_BLUE_STAINED_GLASS:
				return "minecraft:block/light_blue_stained_glass";
			case Material.LIGHT_BLUE_WOOL:
				return "minecraft:block/light_blue_wool";
			case Material.LIGHT_GRAY_CARPET:
				return "minecraft:block/light_gray_carpet";
			case Material.LIGHT_GRAY_CONCRETE:
				return "minecraft:block/light_gray_concrete";
			case Material.LIGHT_GRAY_CONCRETE_POWDER:
				return "minecraft:block/light_gray_concrete_powder";
			case Material.LIGHT_GRAY_GLAZED_TERRACOTTA:
				return "minecraft:block/light_gray_glazed_terracotta";
			case Material.LIGHT_GRAY_STAINED_GLASS:
				return "minecraft:block/light_gray_stained_glass";
			case Material.LIGHT_GRAY_TERRACOTTA:
				return "minecraft:block/light_gray_terracotta";
			case Material.LIGHT_GRAY_WOOL:
				return "minecraft:block/light_gray_wool";
			case Material.LIGHT_WEIGHTED_PRESSURE_PLATE:
				return "minecraft:block/light_weighted_pressure_plate";
			case Material.LIME_CARPET:
				return "minecraft:block/lime_carpet";
			case Material.LIME_CONCRETE:
				return "minecraft:block/lime_concrete";
			case Material.LIME_CONCRETE_POWDER:
				return "minecraft:block/lime_concrete_powder";
			case Material.LIME_GLAZED_TERRACOTTA:
				return "minecraft:block/lime_glazed_terracotta";
			case Material.LIME_STAINED_GLASS:
				return "minecraft:block/lime_stained_glass";
			case Material.LIME_TERRACOTTA:
				return "minecraft:block/lime_terracotta";
			case Material.LIME_WOOL:
				return "minecraft:block/lime_wool";
			case Material.LODESTONE:
				return "minecraft:block/lodestone";
			case Material.LOOM:
				return "minecraft:block/loom";
			case Material.MAGENTA_CARPET:
				return "minecraft:block/magenta_carpet";
			case Material.MAGENTA_CONCRETE:
				return "minecraft:block/magenta_concrete";
			case Material.MAGENTA_CONCRETE_POWDER:
				return "minecraft:block/magenta_concrete_powder";
			case Material.MAGENTA_GLAZED_TERRACOTTA:
				return "minecraft:block/magenta_glazed_terracotta";
			case Material.MAGENTA_STAINED_GLASS:
				return "minecraft:block/magenta_stained_glass";
			case Material.MAGENTA_TERRACOTTA:
				return "minecraft:block/magenta_terracotta";
			case Material.MAGENTA_WOOL:
				return "minecraft:block/magenta_wool";
			case Material.MELON:
				return "minecraft:block/melon";
			case Material.MOSSY_COBBLESTONE:
				return "minecraft:block/mossy_cobblestone";
			case Material.MOSSY_COBBLESTONE_SLAB:
				return "minecraft:block/mossy_cobblestone_slab";
			case Material.MOSSY_COBBLESTONE_STAIRS:
				return "minecraft:block/mossy_cobblestone_stairs";
			case Material.MOSSY_COBBLESTONE_WALL:
				return "minecraft:block/mossy_cobblestone_wall_inventory";
			case Material.MOSSY_STONE_BRICK_SLAB:
				return "minecraft:block/mossy_stone_brick_slab";
			case Material.MOSSY_STONE_BRICK_STAIRS:
				return "minecraft:block/mossy_stone_brick_stairs";
			case Material.MOSSY_STONE_BRICK_WALL:
				return "minecraft:block/mossy_stone_brick_wall_inventory";
			case Material.MOSS_BLOCK:
				return "minecraft:block/moss_block";
			case Material.MOSS_CARPET:
				return "minecraft:block/moss_carpet";
			case Material.MUSHROOM_STEM:
				return "minecraft:block/mushroom_stem_inventory";
			case Material.MYCELIUM:
				return "minecraft:block/mycelium";
			case Material.GOLD_BLOCK:
				return "minecraft:block/gold_block";
			case Material.JUNGLE_SLAB:
				return "minecraft:block/jungle_slab";
			case Material.LIGHT_BLUE_TERRACOTTA:
				return "minecraft:block/light_blue_terracotta";
			case Material.MAGMA_BLOCK:
				return "minecraft:block/magma_block";
			case Material.NETHERITE_BLOCK:
				return "minecraft:block/netherite_block";
			case Material.NETHERRACK:
				return "minecraft:block/netherrack";
			case Material.NETHER_BRICKS:
				return "minecraft:block/nether_bricks";
			case Material.NETHER_BRICK_FENCE:
				return "minecraft:block/nether_brick_fence_inventory";
			case Material.NETHER_BRICK_SLAB:
				return "minecraft:block/nether_brick_slab";
			case Material.NETHER_BRICK_WALL:
				return "minecraft:block/nether_brick_wall_inventory";
			case Material.NETHER_GOLD_ORE:
				return "minecraft:block/nether_gold_ore";
			case Material.NETHER_QUARTZ_ORE:
				return "minecraft:block/nether_quartz_ore";
			case Material.NETHER_WART_BLOCK:
				return "minecraft:block/nether_wart_block";
			case Material.NOTE_BLOCK:
				return "minecraft:block/note_block";
			case Material.OAK_BUTTON:
				return "minecraft:block/oak_button_inventory";
			case Material.OAK_FENCE:
				return "minecraft:block/oak_fence_inventory";
			case Material.OAK_FENCE_GATE:
				return "minecraft:block/oak_fence_gate";
			case Material.OAK_LEAVES:
				return "minecraft:block/oak_leaves";
			case Material.OAK_PLANKS:
				return "minecraft:block/oak_planks";
			case Material.OAK_PRESSURE_PLATE:
				return "minecraft:block/oak_pressure_plate";
			case Material.OAK_SLAB:
				return "minecraft:block/oak_slab";
			case Material.OAK_STAIRS:
				return "minecraft:block/oak_stairs";
			case Material.OAK_TRAPDOOR:
				return "minecraft:block/oak_trapdoor_bottom";
			case Material.OAK_WOOD:
				return "minecraft:block/oak_wood";
			case Material.OBSERVER:
				return "minecraft:block/observer";
			case Material.OBSIDIAN:
				return "minecraft:block/obsidian";
			case Material.ORANGE_CARPET:
				return "minecraft:block/orange_carpet";
			case Material.ORANGE_CONCRETE_POWDER:
				return "minecraft:block/orange_concrete_powder";
			case Material.ORANGE_GLAZED_TERRACOTTA:
				return "minecraft:block/orange_glazed_terracotta";
			case Material.ORANGE_STAINED_GLASS:
				return "minecraft:block/orange_stained_glass";
			case Material.ORANGE_TERRACOTTA:
				return "minecraft:block/orange_terracotta";
			case Material.ORANGE_WOOL:
				return "minecraft:block/orange_wool";
			case Material.OXIDIZED_COPPER:
			case Material.WAXED_OXIDIZED_COPPER:
				return "minecraft:block/oxidized_copper";
			case Material.OXIDIZED_CUT_COPPER:
			case Material.WAXED_OXIDIZED_CUT_COPPER:
				return "minecraft:block/oxidized_cut_copper";
			case Material.OXIDIZED_CUT_COPPER_SLAB:
			case Material.WAXED_OXIDIZED_CUT_COPPER_SLAB:
				return "minecraft:block/oxidized_cut_copper_slab";
			case Material.OXIDIZED_CUT_COPPER_STAIRS:
			case Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS:
				return "minecraft:block/oxidized_cut_copper_stairs";
			case Material.PACKED_ICE:
				return "minecraft:block/packed_ice";
			case Material.PETRIFIED_OAK_SLAB:
				return "minecraft:block/petrified_oak_slab";
			case Material.PINK_CARPET:
				return "minecraft:block/pink_carpet";
			case Material.PINK_CONCRETE:
				return "minecraft:block/pink_concrete";
			case Material.PINK_CONCRETE_POWDER:
				return "minecraft:block/pink_concrete_powder";
			case Material.PINK_GLAZED_TERRACOTTA:
				return "minecraft:block/pink_glazed_terracotta";
			case Material.PINK_STAINED_GLASS:
				return "minecraft:block/pink_stained_glass";
			case Material.PINK_TERRACOTTA:
				return "minecraft:block/pink_terracotta";
			case Material.PINK_WOOL:
				return "minecraft:block/pink_wool";
			case Material.PISTON:
				return "minecraft:block/piston_inventory";
			case Material.PODZOL:
				return "minecraft:block/podzol";
			case Material.POLISHED_ANDESITE:
				return "minecraft:block/polished_andesite";
			case Material.POLISHED_ANDESITE_SLAB:
				return "minecraft:block/polished_andesite_slab";
			case Material.POLISHED_ANDESITE_STAIRS:
				return "minecraft:block/polished_andesite_stairs";
			case Material.POLISHED_BASALT:
				return "minecraft:block/polished_basalt";
			case Material.POLISHED_BLACKSTONE:
				return "minecraft:block/polished_blackstone";
			case Material.POLISHED_BLACKSTONE_BRICKS:
				return "minecraft:block/polished_blackstone_bricks";
			case Material.POLISHED_BLACKSTONE_BRICK_SLAB:
				return "minecraft:block/polished_blackstone_brick_slab";
			case Material.POLISHED_BLACKSTONE_BRICK_STAIRS:
				return "minecraft:block/polished_blackstone_brick_stairs";
			case Material.POLISHED_BLACKSTONE_BRICK_WALL:
				return "minecraft:block/polished_blackstone_brick_wall_inventory";
			case Material.POLISHED_BLACKSTONE_BUTTON:
				return "minecraft:block/polished_blackstone_button_inventory";
			case Material.POLISHED_BLACKSTONE_PRESSURE_PLATE:
				return "minecraft:block/polished_blackstone_pressure_plate";
			case Material.POLISHED_BLACKSTONE_SLAB:
				return "minecraft:block/polished_blackstone_slab";
			case Material.POLISHED_BLACKSTONE_WALL:
				return "minecraft:block/polished_blackstone_wall_inventory";
			case Material.POLISHED_DEEPSLATE:
				return "minecraft:block/polished_deepslate";
			case Material.POLISHED_DEEPSLATE_SLAB:
				return "minecraft:block/polished_deepslate_slab";
			case Material.POLISHED_DEEPSLATE_STAIRS:
				return "minecraft:block/polished_deepslate_stairs";
			case Material.POLISHED_DEEPSLATE_WALL:
				return "minecraft:block/polished_deepslate_wall_inventory";
			case Material.POLISHED_DIORITE:
				return "minecraft:block/polished_diorite";
			case Material.POLISHED_DIORITE_SLAB:
				return "minecraft:block/polished_diorite_slab";
			case Material.POLISHED_DIORITE_STAIRS:
				return "minecraft:block/polished_diorite_stairs";
			case Material.POLISHED_GRANITE:
				return "minecraft:block/polished_granite";
			case Material.POLISHED_GRANITE_SLAB:
				return "minecraft:block/polished_granite_slab";
			case Material.POLISHED_GRANITE_STAIRS:
				return "minecraft:block/polished_granite_stairs";
			case Material.PRISMARINE:
				return "minecraft:block/prismarine";
			case Material.PRISMARINE_BRICKS:
				return "minecraft:block/prismarine_bricks";
			case Material.PRISMARINE_BRICK_SLAB:
				return "minecraft:block/prismarine_brick_slab";
			case Material.PRISMARINE_BRICK_STAIRS:
				return "minecraft:block/prismarine_brick_stairs";
			case Material.PRISMARINE_SLAB:
				return "minecraft:block/prismarine_slab";
			case Material.PRISMARINE_STAIRS:
				return "minecraft:block/prismarine_stairs";
			case Material.PRISMARINE_WALL:
				return "minecraft:block/prismarine_wall_inventory";
			case Material.PUMPKIN:
				return "minecraft:block/pumpkin";
			case Material.PURPLE_CARPET:
				return "minecraft:block/purple_carpet";
			case Material.PURPLE_CONCRETE:
				return "minecraft:block/purple_concrete";
			case Material.PURPLE_CONCRETE_POWDER:
				return "minecraft:block/purple_concrete_powder";
			case Material.PURPLE_GLAZED_TERRACOTTA:
				return "minecraft:block/purple_glazed_terracotta";
			case Material.PURPLE_STAINED_GLASS:
				return "minecraft:block/purple_stained_glass";
			case Material.PURPLE_TERRACOTTA:
				return "minecraft:block/purple_terracotta";
			case Material.PURPLE_WOOL:
				return "minecraft:block/purple_wool";
			case Material.PURPUR_BLOCK:
				return "minecraft:block/purpur_block";
			case Material.PURPUR_PILLAR:
				return "minecraft:block/purpur_pillar";
			case Material.PURPUR_STAIRS:
				return "minecraft:block/purpur_stairs";
			case Material.QUARTZ_BLOCK:
				return "minecraft:block/quartz_block";
			case Material.QUARTZ_BRICKS:
				return "minecraft:block/quartz_bricks";
			case Material.QUARTZ_PILLAR:
				return "minecraft:block/quartz_pillar";
			case Material.QUARTZ_SLAB:
				return "minecraft:block/quartz_slab";
			case Material.QUARTZ_STAIRS:
				return "minecraft:block/quartz_stairs";
			case Material.RAW_COPPER_BLOCK:
				return "minecraft:block/raw_copper_block";
			case Material.RAW_GOLD_BLOCK:
				return "minecraft:block/raw_gold_block";
			case Material.RAW_IRON_BLOCK:
				return "minecraft:block/raw_iron_block";
			case Material.REDSTONE_BLOCK:
				return "minecraft:block/redstone_block";
			case Material.REDSTONE_LAMP:
				return "minecraft:block/redstone_lamp";
			case Material.REDSTONE_ORE:
				return "minecraft:block/redstone_ore";
			case Material.RED_CARPET:
				return "minecraft:block/red_carpet";
			case Material.RED_CONCRETE:
				return "minecraft:block/red_concrete";
			case Material.RED_CONCRETE_POWDER:
				return "minecraft:block/red_concrete_powder";
			case Material.RED_GLAZED_TERRACOTTA:
				return "minecraft:block/red_glazed_terracotta";
			case Material.RED_NETHER_BRICKS:
				return "minecraft:block/red_nether_bricks";
			case Material.RED_NETHER_BRICK_SLAB:
				return "minecraft:block/red_nether_brick_slab";
			case Material.RED_NETHER_BRICK_STAIRS:
				return "minecraft:block/red_nether_brick_stairs";
			case Material.RED_NETHER_BRICK_WALL:
				return "minecraft:block/red_nether_brick_wall_inventory";
			case Material.RED_SAND:
				return "minecraft:block/red_sand";
			case Material.RED_SANDSTONE:
				return "minecraft:block/red_sandstone";
			case Material.RED_SANDSTONE_SLAB:
				return "minecraft:block/red_sandstone_slab";
			case Material.RED_SANDSTONE_STAIRS:
				return "minecraft:block/red_sandstone_stairs";
			case Material.RED_SANDSTONE_WALL:
				return "minecraft:block/red_sandstone_wall_inventory";
			case Material.RED_STAINED_GLASS:
				return "minecraft:block/red_stained_glass";
			case Material.RED_TERRACOTTA:
				return "minecraft:block/red_terracotta";
			case Material.RED_WOOL:
				return "minecraft:block/red_wool";
			case Material.REPEATING_COMMAND_BLOCK:
				return "minecraft:block/repeating_command_block";
			case Material.RESPAWN_ANCHOR:
				return "minecraft:block/respawn_anchor_0";
			case Material.ROOTED_DIRT:
				return "minecraft:block/rooted_dirt";
			case Material.SAND:
				return "minecraft:block/sand";
			case Material.SANDSTONE:
				return "minecraft:block/sandstone";
			case Material.SANDSTONE_SLAB:
				return "minecraft:block/sandstone_slab";
			case Material.SANDSTONE_STAIRS:
				return "minecraft:block/sandstone_stairs";
			case Material.SANDSTONE_WALL:
				return "minecraft:block/sandstone_wall_inventory";
			case Material.SCAFFOLDING:
				return "minecraft:block/scaffolding_stable";
			case Material.NETHER_BRICK_STAIRS:
				return "minecraft:block/nether_brick_stairs";
			case Material.OAK_LOG:
				return "minecraft:block/oak_log";
			case Material.ORANGE_CONCRETE:
				return "minecraft:block/orange_concrete";
			case Material.POLISHED_BLACKSTONE_STAIRS:
				return "minecraft:block/polished_blackstone_stairs";
			case Material.PURPUR_SLAB:
				return "minecraft:block/purpur_slab";
			case Material.RED_MUSHROOM_BLOCK:
				return "minecraft:block/red_mushroom_block_inventory";
			case Material.COBBLED_DEEPSLATE_STAIRS:
				return "minecraft:block/cobbled_deepslate_stairs";
			case Material.SCULK_SENSOR:
				return "minecraft:block/sculk_sensor_inactive";
			case Material.SEA_LANTERN:
				return "minecraft:block/sea_lantern";
			case Material.SHROOMLIGHT:
				return "minecraft:block/shroomlight";
			case Material.SLIME_BLOCK:
				return "minecraft:block/slime_block";
			case Material.SMALL_DRIPLEAF:
				return "minecraft:block/small_dripleaf_top";
			case Material.SMITHING_TABLE:
				return "minecraft:block/smithing_table";
			case Material.SMOKER:
				return "minecraft:block/smoker";
			case Material.SMOOTH_BASALT:
				return "minecraft:block/smooth_basalt";
			case Material.SMOOTH_QUARTZ:
				return "minecraft:block/smooth_quartz";
			case Material.SMOOTH_QUARTZ_SLAB:
				return "minecraft:block/smooth_quartz_slab";
			case Material.SMOOTH_QUARTZ_STAIRS:
				return "minecraft:block/smooth_quartz_stairs";
			case Material.SMOOTH_RED_SANDSTONE:
				return "minecraft:block/smooth_red_sandstone";
			case Material.SMOOTH_RED_SANDSTONE_SLAB:
				return "minecraft:block/smooth_red_sandstone_slab";
			case Material.SMOOTH_SANDSTONE:
				return "minecraft:block/smooth_sandstone";
			case Material.SMOOTH_SANDSTONE_SLAB:
				return "minecraft:block/smooth_sandstone_slab";
			case Material.SMOOTH_SANDSTONE_STAIRS:
				return "minecraft:block/smooth_sandstone_stairs";
			case Material.SMOOTH_STONE:
				return "minecraft:block/smooth_stone";
			case Material.SMOOTH_STONE_SLAB:
				return "minecraft:block/smooth_stone_slab";
			case Material.SNOW:
				return "minecraft:block/snow_height2";
			case Material.SNOW_BLOCK:
				return "minecraft:block/snow_block";
			case Material.SOUL_SAND:
				return "minecraft:block/soul_sand";
			case Material.SOUL_SOIL:
				return "minecraft:block/soul_soil";
			case Material.SPAWNER:
				return "minecraft:block/spawner";
			case Material.SPONGE:
				return "minecraft:block/sponge";
			case Material.SPORE_BLOSSOM:
				return "minecraft:block/spore_blossom";
			case Material.SPRUCE_BUTTON:
				return "minecraft:block/spruce_button_inventory";
			case Material.SPRUCE_FENCE:
				return "minecraft:block/spruce_fence_inventory";
			case Material.SPRUCE_FENCE_GATE:
				return "minecraft:block/spruce_fence_gate";
			case Material.SPRUCE_LEAVES:
				return "minecraft:block/spruce_leaves";
			case Material.SPRUCE_LOG:
				return "minecraft:block/spruce_log";
			case Material.SPRUCE_PLANKS:
				return "minecraft:block/spruce_planks";
			case Material.SPRUCE_PRESSURE_PLATE:
				return "minecraft:block/spruce_pressure_plate";
			case Material.SPRUCE_SLAB:
				return "minecraft:block/spruce_slab";
			case Material.SPRUCE_STAIRS:
				return "minecraft:block/spruce_stairs";
			case Material.SPRUCE_TRAPDOOR:
				return "minecraft:block/spruce_trapdoor_bottom";
			case Material.SPRUCE_WOOD:
				return "minecraft:block/spruce_wood";
			case Material.STICKY_PISTON:
				return "minecraft:block/sticky_piston_inventory";
			case Material.STONECUTTER:
				return "minecraft:block/stonecutter";
			case Material.STONE_BRICK_SLAB:
				return "minecraft:block/stone_brick_slab";
			case Material.STONE_BRICK_STAIRS:
				return "minecraft:block/stone_brick_stairs";
			case Material.STONE_BRICK_WALL:
				return "minecraft:block/stone_brick_wall_inventory";
			case Material.STONE_PRESSURE_PLATE:
				return "minecraft:block/stone_pressure_plate";
			case Material.STONE_SLAB:
				return "minecraft:block/stone_slab";
			case Material.STONE_STAIRS:
				return "minecraft:block/stone_stairs";
			case Material.STRIPPED_ACACIA_LOG:
				return "minecraft:block/stripped_acacia_log";
			case Material.STRIPPED_ACACIA_WOOD:
				return "minecraft:block/stripped_acacia_wood";
			case Material.STRIPPED_BIRCH_LOG:
				return "minecraft:block/stripped_birch_log";
			case Material.STRIPPED_BIRCH_WOOD:
				return "minecraft:block/stripped_birch_wood";
			case Material.STRIPPED_CRIMSON_STEM:
				return "minecraft:block/stripped_crimson_stem";
			case Material.STRIPPED_DARK_OAK_LOG:
				return "minecraft:block/stripped_dark_oak_log";
			case Material.STRIPPED_DARK_OAK_WOOD:
				return "minecraft:block/stripped_dark_oak_wood";
			case Material.STRIPPED_JUNGLE_LOG:
				return "minecraft:block/stripped_jungle_log";
			case Material.STRIPPED_JUNGLE_WOOD:
				return "minecraft:block/stripped_jungle_wood";
			case Material.STRIPPED_OAK_LOG:
				return "minecraft:block/stripped_oak_log";
			case Material.STRIPPED_OAK_WOOD:
				return "minecraft:block/stripped_oak_wood";
			case Material.STRIPPED_SPRUCE_LOG:
				return "minecraft:block/stripped_spruce_log";
			case Material.STRIPPED_SPRUCE_WOOD:
				return "minecraft:block/stripped_spruce_wood";
			case Material.STRIPPED_WARPED_HYPHAE:
				return "minecraft:block/stripped_warped_hyphae";
			case Material.STRIPPED_WARPED_STEM:
				return "minecraft:block/stripped_warped_stem";
			case Material.STRUCTURE_BLOCK:
				return "minecraft:block/structure_block";
			case Material.TARGET:
				return "minecraft:block/target";
			case Material.TERRACOTTA:
				return "minecraft:block/terracotta";
			case Material.TINTED_GLASS:
				return "minecraft:block/tinted_glass";
			case Material.TUBE_CORAL_BLOCK:
				return "minecraft:block/tube_coral_block";
			case Material.WARPED_BUTTON:
				return "minecraft:block/warped_button_inventory";
			case Material.WARPED_FENCE:
				return "minecraft:block/warped_fence_inventory";
			case Material.WARPED_FENCE_GATE:
				return "minecraft:block/warped_fence_gate";
			case Material.WARPED_HYPHAE:
				return "minecraft:block/warped_hyphae";
			case Material.WARPED_NYLIUM:
				return "minecraft:block/warped_nylium";
			case Material.WARPED_PLANKS:
				return "minecraft:block/warped_planks";
			case Material.WARPED_PRESSURE_PLATE:
				return "minecraft:block/warped_pressure_plate";
			case Material.WARPED_SLAB:
				return "minecraft:block/warped_slab";
			case Material.WARPED_STAIRS:
				return "minecraft:block/warped_stairs";
			case Material.WARPED_STEM:
				return "minecraft:block/warped_stem";
			case Material.WARPED_TRAPDOOR:
				return "minecraft:block/warped_trapdoor_bottom";
			case Material.WARPED_WART_BLOCK:
				return "minecraft:block/warped_wart_block";
			case Material.WAXED_WEATHERED_COPPER:
			case Material.WEATHERED_COPPER:
				return "minecraft:block/weathered_copper";
			case Material.WAXED_WEATHERED_CUT_COPPER:
			case Material.WEATHERED_CUT_COPPER:
				return "minecraft:block/weathered_cut_copper";
			case Material.WAXED_WEATHERED_CUT_COPPER_SLAB:
			case Material.WEATHERED_CUT_COPPER_SLAB:
				return "minecraft:block/weathered_cut_copper_slab";
			case Material.WAXED_WEATHERED_CUT_COPPER_STAIRS:
			case Material.WEATHERED_CUT_COPPER_STAIRS:
				return "minecraft:block/weathered_cut_copper_stairs";
			case Material.WET_SPONGE:
				return "minecraft:block/wet_sponge";
			case Material.WHITE_CARPET:
				return "minecraft:block/white_carpet";
			case Material.WHITE_CONCRETE:
				return "minecraft:block/white_concrete";
			case Material.WHITE_CONCRETE_POWDER:
				return "minecraft:block/white_concrete_powder";
			case Material.WHITE_GLAZED_TERRACOTTA:
				return "minecraft:block/white_glazed_terracotta";
			case Material.WHITE_TERRACOTTA:
				return "minecraft:block/white_terracotta";
			case Material.WHITE_WOOL:
				return "minecraft:block/white_wool";
			case Material.YELLOW_CARPET:
				return "minecraft:block/yellow_carpet";
			case Material.YELLOW_CONCRETE:
				return "minecraft:block/yellow_concrete";
			case Material.YELLOW_CONCRETE_POWDER:
				return "minecraft:block/yellow_concrete_powder";
			case Material.YELLOW_GLAZED_TERRACOTTA:
				return "minecraft:block/yellow_glazed_terracotta";
			case Material.YELLOW_STAINED_GLASS:
				return "minecraft:block/yellow_stained_glass";
			case Material.YELLOW_TERRACOTTA:
				return "minecraft:block/yellow_terracotta";
			case Material.YELLOW_WOOL:
				return "minecraft:block/yellow_wool";
			case Material.SMOOTH_RED_SANDSTONE_STAIRS:
				return "minecraft:block/smooth_red_sandstone_stairs";
			case Material.STONE_BUTTON:
				return "minecraft:block/stone_button_inventory";
			case Material.STRIPPED_CRIMSON_HYPHAE:
				return "minecraft:block/stripped_crimson_hyphae";
			case Material.TNT:
				return "minecraft:block/tnt";
			case Material.TUFF:
				return "minecraft:block/tuff";
			case Material.WHITE_STAINED_GLASS:
				return "minecraft:block/white_stained_glass";

		}
		return null;
	}
}